export enum BusinessType {
  CAFE = 'CAFE',
  HOTEL = 'HOTEL',
  HOSPITAL = 'HOSPITAL',
  SCHOOL = 'SCHOOL',
  OFFICE = 'OFFICE',
  PUBLIC = 'PUBLIC',
  CAFETERIA = 'CAFETERIA',
  LOBBY = 'LOBBY',
  LOUNGE = 'LOUNGE',
}
