version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    ports:
      - '8080:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
