export const ENV_DB_DATABASE_KEY = 'DB_DATABASE';
export const ENV_DB_USERNAME_KEY = 'DB_USERNAME';
export const ENV_DB_PASSWORD_KEY = 'DB_PASSWORD';
export const ENV_DB_PORT_KEY = 'DB_PORT';
export const ENV_DB_HOST_KEY = 'DB_HOST';

export const ENV_PORT_KEY = 'PORT';

export const ENV_KAKAO_CLIENTID_KEY = 'KAKAO_CLIENTID';
export const ENV_KAKAO_SECRET_KEY_KEY = 'KAKAO_SECRET_KEY';
export const ENV_KAKAO_CALLBACK_URL_KEY = 'KAKAO_CALLBACK_URL';

export const ENV_NAVER_CLIENTID_KEY = 'NAVER_CLIENTID';
export const ENV_NAVER_SECRET_KEY_KEY = 'NAVER_SECRET_KEY';
export const ENV_NAVER_CALLBACK_URL_KEY = 'NAVER_CALLBACK_URL';

export const ENV_JWT_SECRET_KEY_KEY = 'JWT_SECRET_KEY';

export const ENV_CLIENT_URL_KEY = 'CLIENT_URL';

export const ENV_SMS_ACCESS_KEY_KEY = 'SMS_ACCESS_KEY';
export const ENV_SMS_SECRET_KEY_KEY = 'SMS_SECRET_KEY';
export const ENV_SMS_SERVICE_ID_KEY = 'SMS_SERVICE_ID';
